version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:7.4
    steps:
      - checkout
      - run: sudo apt update
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: sudo pecl install mongodb
      - run: echo -e "extension=mongodb.so" | sudo tee /etc/php/7.4/cli/php.ini > /dev/null
      - run: composer install -n --prefer-dist
      - run: cp .env.example .env
      - run: php artisan key:generate
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: ./vendor/bin/phpunit

orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  build-and-deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: main
